version: "3.1"

services:

  nginx:
    image: nginx:latest
    restart: unless-stopped
    volumes:
      - ./:/var/www
      - ./_docker/nginx/conf.d:/etc/nginx/conf.d
    ports:
      - 8875:80
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.shatynskyj.entrypoints=https"
      - "traefik.http.routers.shatynskyj.rule=Host(`shatynskyj.in.ua`)"
      - "traefik.http.routers.shatynskyj.tls=true"
      - "traefik.http.routers.shatynskyj.tls.certresolver=letsEncrypt"
    networks:
      - traefik-public
    depends_on:
      - app
    container_name: shatynskyj_nginx

  app:
    image: php:8.1-fpm
    volumes:
      - ./:/var/www
    user: 1000:1000
    container_name: shatynskyj_app
    restart: unless-stopped

networks:
  traefik-public:
    external: true
